# Generated by Django 5.0 on 2023-12-19 16:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.IntegerField()),
                ('fechaAfiliacion', models.DateField()),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CondicionDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('P', 'aPagar'), ('C', 'contado')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CondicionDePagoArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('ArticuloId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.articulo')),
                ('CondicionDePagoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.condiciondepago')),
            ],
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precioArticulo', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('ArticuloId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEmision', models.DateField(default=datetime.datetime(2023, 12, 19, 16, 32, 27, 106455, tzinfo=datetime.timezone.utc))),
                ('fechaVencimiento', models.DateField()),
                ('importeCancelado', models.FloatField(default=0)),
                ('importeTotal', models.FloatField()),
                ('tipo', models.CharField(choices=[('A', 'facturaA'), ('B', 'facturaB'), ('C', 'facturaC'), ('N', 'notaCredito')], max_length=1)),
                ('AfiliadoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.afiliado')),
                ('CondicionDePagoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.condiciondepago')),
                ('VentaDetalleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.ventadetalle')),
            ],
        ),
    ]
