# Generated by Django 5.0 on 2023-12-19 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fechaEmision',
            field=models.DateField(default=datetime.datetime(2023, 12, 19, 18, 53, 18, 845673, tzinfo=datetime.timezone.utc)),
        ),
    ]
