# Generated by Django 5.0 on 2023-12-20 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_venta_fechaemision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='AfiliadoId',
            new_name='Afiliado',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='CondicionDePagoId',
            new_name='CondicionDePago',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='VentaDetalleId',
            new_name='VentaDetalle',
        ),
        migrations.AlterField(
            model_name='venta',
            name='fechaEmision',
            field=models.DateField(default=datetime.datetime(2023, 12, 20, 3, 14, 49, 771723, tzinfo=datetime.timezone.utc)),
        ),
    ]
