# Generated by Django 5.0 on 2023-12-20 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_rename_afiliadoid_venta_afiliado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condiciondepagoarticulo',
            old_name='CondicionDePagoId',
            new_name='CondicionDePago',
        ),
        migrations.RenameField(
            model_name='ventadetalle',
            old_name='ArticuloId',
            new_name='Articulo',
        ),
        migrations.AlterField(
            model_name='venta',
            name='fechaEmision',
            field=models.DateField(default=datetime.datetime(2023, 12, 20, 3, 19, 5, 181995, tzinfo=datetime.timezone.utc)),
        ),
    ]
