# Generated by Django 5.0 on 2023-12-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_venta_fechaemision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condiciondepago',
            name='tipo',
            field=models.CharField(choices=[('A Pagar', 'aPagar'), ('Contado', 'contado')], max_length=20),
        ),
    ]
