# Generated by Django 5.0 on 2023-12-24 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_remove_venta_ventadetalle_ventadetalle_venta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fechaEmision',
            field=models.DateField(default=datetime.date(2023, 12, 24)),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fechaVencimiento',
            field=models.DateField(default=datetime.date(2023, 12, 24)),
        ),
        migrations.AlterField(
            model_name='venta',
            name='importeTotal',
            field=models.FloatField(default=0),
        ),
    ]
